### ISSUE TITLE
Requisitos interface principal de preservCutGeo 

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preservDataViz#2]
Requisitos de software relativos ao mapa e interatividade para os dados de `git.digital-guard.org/preservCutGeo-{country}{year}`.

A comunicação e acordos definidores dos requisitos foram baseados em 3 fontes:

1. [`DraftReference`](http://git.digital-guard.org/preservDataViz/blob/main/src/preservCutGeo/originalDraft.html), cóigo-fonte página original com "software-rascunho de referência", utilizado como prova de conceito ([operante](https://digital-guard.github.io/preservDataViz/src/preservCutGeo/originalDraft.html)) e referencial para a solicitação de características similares e características distintas.

2. Software em evolução, em sequência de testes-refinamentos dos resquisitos. https://digital-guard.github.io/preservDataViz/  [incremental development](https://en.wikipedia.org/wiki/Incremental_build_model)

3. Dados de  http://git.digital-guard.org/preservCutGeo-BR2021 como referência durante o desenvolvimento incremental.

## Requisitos

Com base no DraftReference, solicita-se manter **características semelhantes** às seguintes, ou efetuando eventuais melhoras  no [software requisitado](https://github.com/digital-guard/preservDataViz/blob/main/src/preservCutGeo/index.html):

- [x] Ajustar onMouseOver para não deixar rastros
- [x] Mostrar ícones menores no primeiro zoom dos pontos
- [x] Mostrar icones normais e trocar imagem de fundo para satélite MapBox (ou algo que não apague) quando zoom maior.
- [x] #3
- [x] Detector de URL para já abrir nos pontos desejados 
- [x] Limitação no zoom-out.

Com base no DraftReference, solicita-se **características distintas** com as seguintes  diferenças:
- [x] Tons de cinza no *tile* (fundo) do mosaico, e colorido no *tile* dos pontos ;
- [x] Colorir o mosaico com a densidade de pontos da célula;
- [ ] usar "pin icons"  maiores e sombreados (como no visualizador GeoJSON do Github) quando zoom bem próximo, com apenas alguns pontos e sua via.
- [x]  sumir com as letras no extremo de zoom-out. Ver https://stackoverflow.com/a/37971356/287948
- [ ] quando está no superZoom o onmouse-over mostra e o on-click fixa, para poder comparar dois pontos. Quando segundo click, desfixa.
- [x]  quando zoom-out para mosaico os labels fixados por click desaparecem (clean).
- [x]  interface inferior com checkboxes para ligar/desligar comportamentos (analogo ao inferior de https://ppkrauss.github.io/Sfc4q/ )
- [x]  Itens de checkbox:  habilitar/desabilitar "onClick fixa/desfixa rótulo" (senão como no Github nunca fixa);  habilitar/desabilitar  limpeza do layer de pontos depois do zoom-out.
- [x] tableSort na tabela do seletor externo

## Homologação

* dados definidos em BeloHorizonte
* navegadores Chorme e Firefox. Firefox Android v96+; Firefox   Desktop v91.5+;  Chrome for Android; Chrome Desktop v96+; iPhone.

Requisitos para *mobile* e *desktop* podem ser distintos, a versão *mobile* pode ser mais simples e menos interativa.

**Comment by ppKrauss** [comment]
Sobre os [itens pendentes](#issue-1113941800), precisa de uma especificação mais detalhada ou a informal foi suficiente?

1. usar "pin icons"  maiores e sombreados ...
2.  sumir com as letras no extremo de zoom-out...
3. quando está no superZoom o onmouse-over mostra e o on-click fixa, ...
4. quando zoom-out para mosaico os labels fixados por click desaparecem (clean).
5. interface inferior com checkboxes para ligar/desligar comportamentos ...
6.  Itens de checkbox:  habilitar/desabilitar "onClick fixa/desfixa rótulo" ..

**Comment by elpbatista** [comment]
Creo que con esa información es suficiente para tener una idea. Los puntos del 1 al 4 requieren trucar Leaflet para que se comporte de manera distinta a la que fue diseñado. Los puntos 5 y 6 se resuelven usando solo JavaScript, puede incluir un pto 7 = TableSort.

**Comment by ppKrauss** [comment]
> Los puntos 5 y 6 se resuelven usando solo JavaScript, puede incluir un pto 7 = TableSort.

Ok, criei o 7.  Vamos então priorizar do 5 ao 7. Do 1 ao 4 você decide se vale a pena perder mais tempo, veja o que pode ser feito sem muito trabalho.

**Comment by ppKrauss** [comment]
detalhando o requisito 

> 5\. interface inferior com checkboxes para ligar/desligar comportamentos

usuários mais técnicos precisarão visualizar os pontos já baixados e ir acumulando alguns quadrantes no navegador... Como na ilustração abaixo. Assim o checkbox é para ativar "memória dos pontos" ou "desativar apagando tudo"

![](https://raw.githubusercontent.com/digital-guard/preservDataViz/main/docs/assets/densities-exampleAt_7h2wqz.png)

**Comment by ppKrauss** [comment]
**Novo requisito**: talvez demande registro de Token mas queremos que os mesmos usuários especiais possam visualizar os pontos de endereço (zoom) em **3 tipos diferentes de tile de fundo**:  Google, Bing e OSM. Por enquanto só temos OSM.

A ideia é conferir se há ou não deslocamento relativo às ruas em diferentes fornecedores de Tile.

**Comment by elpbatista** [comment]
Selector de mapas de fondo ¡hecho¡ 
Ahora tiene 4 mapas distintos, todos proporcionados por Mapbox, pero sería solo buscar los de Google y Bing (si es que tienen el servicio disponible) y sustituirlos en main.js

**Comment by elpbatista** [comment]
Table sort resuelto. Falta agregar algunos estilos para indicar el orden ascendente o descendente (flechas)

**Comment by ppKrauss** [comment]
Obrigado @elpbatista, o principal foi implementado!
Próximo passo: @0e1 vai fazer o ajuste fino e desenvolver o template da página.

**Comment by ppKrauss** [comment]
Ainda pendente resolver zoom, como era antes: remove o layer do mosaico quando dá zoom nos pontos.
