### ISSUE TITLE
Seletor externo de geohashes para saltar direto sem uso do mapa

### ISSUE THREAD

**Issue by elpbatista** [digital-guard/preservDataViz#3]
Solo puede ser resuelto parcialmente porque Leaflet no implementa una interfaz para manejar features individuales

**Comment by elpbatista** [comment]
Leaflet no implementa una interfaz (función getFeature()) que permita recuperar una elemento una vez agregado al mapa desde un entorno diferente al mapa mismo. En versiones anteriores lo resolvía con un plugin "Leaflet-select" pero ya no funciona más. La solución parcial de selector externo es una lista con enlaces que conformen la cadena de conexión href=URL+ghs pero sin la posibilidad de resaltar en el mapa de mosaicos cuál a es el que se está haciendo referencia desde la lista externa. Eso está resuelto en OpenLayers. 
Se podría extender Leaflet pero en mi opinión lo más sensato sería cambiar a OpenLayers que tiene otras posibilidades de interacción.
Esta limitación también influye cuando se necesita modificar de manera dinámica lo que ya está representado en el mapa como el tipo o el tamaño de los marcadores que está definido en las options en lugar de en el style. Leaflet solo proporciona interfaz con el style (getStyle(), setStyle(), resetStyle()) y afecta a la capa completa al no poder acceder a un elemento específico.
Se podría usar una capa diferente para cada elemento lo cual complicaría demasiado la aplicación y además es ineficiente en cuanto al uso de recursos del browser (memoria)

**Comment by ppKrauss** [comment]
Seria fácil ter uma interface de ordenar as colunas da tabela? ao clicar num icone ou no cabeçalho da coluna, fica tudo ordenado por aquela coluna.

![image](https://user-images.githubusercontent.com/1651447/151903875-70427133-a175-415b-ac2c-4382c04055f5.png)

**Comment by elpbatista** [comment]
La mayoría de los frameworks como JQuery o Bootstrap ya vienen con eso implementado. En este caso se podría usar [Tablesort](https://github.com/tristen/tablesort) para JavaScript puro. Yo no lo uso hace años pero funcionaba bien.

**Comment by ppKrauss** [comment]
> En este caso se podría usar [Tablesort](https://github.com/tristen/tablesort) para JavaScript puro. Yo no lo uso hace años pero funcionaba bien.

Ok, pode usar Tablesort
