### ISSUE TITLE
falhas menores no mosaico

### ISSUE THREAD

**Issue by ppKrauss** [digital-guard/preservDataViz#4]
Usando versão atual, [`2fbff254`](https://github.com/digital-guard/preservDataViz/tree/2fbff254b7593ea4114356cbee6a6485d76fe6b7) , de https://digital-guard.github.io/preservDataViz/src/preservCutGeo/index.html

Bugs:

1. O mosaico deveria ter fundo (tile) em tons de cinza, para garantir destaque do mosaico.
2. o zoom-out do mosaico gera uma recarga, quando deveria apenas desabilitar (stop) o zoom.

**Comment by elpbatista** [comment]
1. ¡Arreglado! Ahora usa solo un mapa de fondo: el estilo light-v10 de Mapbox (solo tonos de gris)
2. No es una recarga. Cuando el zoom es menor del permitido minZoom el mapa se regenera y se acomoda otra vez a los parámetros iniciales. Eso es de Leaflet, no está controlado por el script. Debería ser imperceptible pero como esta página es demasiado grande (Hay muchos nodos en el DOM) ocupa demasiado en memoria y ocurre tan despacio que es perceptible para el usuario.

**Comment by ppKrauss** [comment]
Outro detalhe, está sendo gerado um ponto por célula no mosaico. Repare  **1⋅** abaixo

![image](https://user-images.githubusercontent.com/1651447/151887883-744affba-c994-4385-b315-7151a4cf2c4a.png)

**Comment by elpbatista** [comment]
Ese punto es el truco que usa Leaflet para poner la etiqueta y poder usar el tooltip para mostrar el mensaje "cliché aquí..." Debería estar oculto porque su dimensión es 0px. Voy a mirar como corregirlo porque es ahora que apareció, antes no lo había notado.

**Comment by ppKrauss** [comment]
> No es una recarga. Cuando el zoom es menor del permitido minZoom el mapa se regenera y se acomoda otra vez a los parámetros iniciales. (...)

Creio que o mais correto seja simplesmente limitar, "do nothing" quando usuário tenta zoom-out  para além do limite permitido... O Leaflet tem sim parâmetros e comportamento adequado para isso.

**Comment by elpbatista** [comment]
Ahora mismo es el comportamiento sin parámetros. Solo limitado el zoom-out. Antes estaba limitando el bbox pero la respuesta del mapa era más inestable (imagen temblorosa) Así lo hace por defecto Leaflet, no creo que pueda ser modificado fácilmente

**Comment by ppKrauss** [comment]
Ok, tudo resolvido
